from __future__ import annotations


BROADCAST_TEMPLATE_NOT_FOUND = 'BROADCAST_TEMPLATE_NOT_FOUND'
BROADCAST_TEMPLATE_NAME_DUPLICATE = 'BROADCAST_TEMPLATE_NAME_DUPLICATE'
BROADCAST_TEMPLATE_CONTENT_REQUIRED = 'BROADCAST_TEMPLATE_CONTENT_REQUIRED'
BROADCAST_VARIABLE_PROFILE_INVALID = 'BROADCAST_VARIABLE_PROFILE_INVALID'
BROADCAST_GROUP_RULE_NOT_FOUND = 'BROADCAST_GROUP_RULE_NOT_FOUND'
BROADCAST_GROUP_RULE_DUPLICATE = 'BROADCAST_GROUP_RULE_DUPLICATE'
BROADCAST_GROUP_RULE_REGEX_INVALID = 'BROADCAST_GROUP_RULE_REGEX_INVALID'
BROADCAST_GROUP_NAME_DUPLICATE = 'BROADCAST_GROUP_NAME_DUPLICATE'
BROADCAST_GROUP_NAME_NOT_FOUND = 'BROADCAST_GROUP_NAME_NOT_FOUND'
BROADCAST_SCOPE_REQUIRED = 'BROADCAST_SCOPE_REQUIRED'
TEMPLATE_RENDER_INPUT_INVALID = 'TEMPLATE_RENDER_INPUT_INVALID'


class BroadcastError(Exception):
    def __init__(
        self,
        code: str,
        message: str | None = None,
        details: list[str] | None = None,
    ) -> None:
        super().__init__(code)
        self.code = code
        self.message = message or code
        self.details = details or []
