from __future__ import annotations


BROADCAST_TEMPLATE_NOT_FOUND = 'BROADCAST_TEMPLATE_NOT_FOUND'
BROADCAST_TEMPLATE_NAME_DUPLICATE = 'BROADCAST_TEMPLATE_NAME_DUPLICATE'
BROADCAST_TEMPLATE_CONTENT_REQUIRED = 'BROADCAST_TEMPLATE_CONTENT_REQUIRED'
BROADCAST_VARIABLE_PROFILE_INVALID = 'BROADCAST_VARIABLE_PROFILE_INVALID'
BROADCAST_GROUP_RULE_NOT_FOUND = 'BROADCAST_GROUP_RULE_NOT_FOUND'
BROADCAST_GROUP_RULE_DUPLICATE = 'BROADCAST_GROUP_RULE_DUPLICATE'
BROADCAST_GROUP_RULE_REGEX_INVALID = 'BROADCAST_GROUP_RULE_REGEX_INVALID'
BROADCAST_GROUP_NAME_DUPLICATE = 'BROADCAST_GROUP_NAME_DUPLICATE'
BROADCAST_GROUP_NAME_NOT_FOUND = 'BROADCAST_GROUP_NAME_NOT_FOUND'
BROADCAST_SCOPE_REQUIRED = 'BROADCAST_SCOPE_REQUIRED'
TEMPLATE_RENDER_INPUT_INVALID = 'TEMPLATE_RENDER_INPUT_INVALID'
BROADCAST_IMPORT_FILE_INVALID = 'BROADCAST_IMPORT_FILE_INVALID'
BROADCAST_IMPORT_VARIABLE_PROFILE_REQUIRED = 'BROADCAST_IMPORT_VARIABLE_PROFILE_REQUIRED'
BROADCAST_IMPORT_GROUP_FIELD_REQUIRED = 'BROADCAST_IMPORT_GROUP_FIELD_REQUIRED'
BROADCAST_IMPORT_FIELDS_MISSING = 'BROADCAST_IMPORT_FIELDS_MISSING'
BROADCAST_IMPORT_REMATCH_FIELDS_MISSING = 'BROADCAST_IMPORT_REMATCH_FIELDS_MISSING'
BROADCAST_IMPORT_NOT_FOUND = 'BROADCAST_IMPORT_NOT_FOUND'
BROADCAST_IMPORT_READY_DRAFT_EXISTS = 'BROADCAST_IMPORT_READY_DRAFT_EXISTS'
BROADCAST_IMPORT_GROUP_NOT_FOUND = 'BROADCAST_IMPORT_GROUP_NOT_FOUND'
BROADCAST_DRAFT_NOT_FOUND = 'BROADCAST_DRAFT_NOT_FOUND'
BROADCAST_DRAFT_BODY_EMPTY = 'BROADCAST_DRAFT_BODY_EMPTY'
BROADCAST_DRAFT_STATUS_INVALID = 'BROADCAST_DRAFT_STATUS_INVALID'
BROADCAST_DRAFT_INVALID_CONFIRM_FORBIDDEN = 'BROADCAST_DRAFT_INVALID_CONFIRM_FORBIDDEN'
BROADCAST_DRAFT_STALE_CONFIRM_FORBIDDEN = 'BROADCAST_DRAFT_STALE_CONFIRM_FORBIDDEN'
BROADCAST_DRAFT_SCOPE_MISMATCH = 'BROADCAST_DRAFT_SCOPE_MISMATCH'
BROADCAST_EXECUTION_BATCH_NOT_FOUND = 'BROADCAST_EXECUTION_BATCH_NOT_FOUND'
BROADCAST_EXECUTION_TASK_NOT_FOUND = 'BROADCAST_EXECUTION_TASK_NOT_FOUND'
BROADCAST_EXECUTION_EVIDENCE_NOT_AVAILABLE = 'BROADCAST_EXECUTION_EVIDENCE_NOT_AVAILABLE'
BROADCAST_EXECUTION_DRAFT_NOT_READY = 'BROADCAST_EXECUTION_DRAFT_NOT_READY'
BROADCAST_EXECUTION_DRAFT_STALE = 'BROADCAST_EXECUTION_DRAFT_STALE'
BROADCAST_EXECUTION_SCOPE_MISMATCH = 'BROADCAST_EXECUTION_SCOPE_MISMATCH'
BROADCAST_EXECUTION_MODE_INVALID = 'BROADCAST_EXECUTION_MODE_INVALID'
BROADCAST_EXECUTION_DRAFT_LIMIT_EXCEEDED = 'BROADCAST_EXECUTION_DRAFT_LIMIT_EXCEEDED'
BROADCAST_EXECUTION_TASK_STATUS_INVALID = 'BROADCAST_EXECUTION_TASK_STATUS_INVALID'
BROADCAST_EXECUTION_SAFETY_LOCK_REQUIRED = 'BROADCAST_EXECUTION_SAFETY_LOCK_REQUIRED'
BROADCAST_EXECUTION_SEND_UNSUPPORTED = 'BROADCAST_EXECUTION_SEND_UNSUPPORTED'
BROADCAST_EXECUTION_SEND_TRIGGERED = 'BROADCAST_EXECUTION_SEND_TRIGGERED'
BROADCAST_EXECUTION_RUNTIME_TASK_ID_CONFLICT = 'BROADCAST_EXECUTION_RUNTIME_TASK_ID_CONFLICT'
BROADCAST_EXECUTION_RESULT_PERSISTENCE_FAILED = 'BROADCAST_EXECUTION_RESULT_PERSISTENCE_FAILED'
BROADCAST_EXECUTION_BATCH_STATUS_INVALID = 'BROADCAST_EXECUTION_BATCH_STATUS_INVALID'
BROADCAST_EXECUTION_HEALTH_CHECK_FAILED = 'BROADCAST_EXECUTION_HEALTH_CHECK_FAILED'
BROADCAST_EXECUTION_CONFIRMATION_REQUIRED = 'BROADCAST_EXECUTION_CONFIRMATION_REQUIRED'
BROADCAST_EXECUTION_CONFIRMATION_INVALID = 'BROADCAST_EXECUTION_CONFIRMATION_INVALID'
BROADCAST_EXECUTION_CONFIRMATION_EXPIRED = 'BROADCAST_EXECUTION_CONFIRMATION_EXPIRED'
BROADCAST_EXECUTION_SEND_DISABLED = 'BROADCAST_EXECUTION_SEND_DISABLED'
ATTACHMENT_UNSUPPORTED_TYPE = 'ATTACHMENT_UNSUPPORTED_TYPE'
ATTACHMENT_FILE_TOO_LARGE = 'ATTACHMENT_FILE_TOO_LARGE'
ATTACHMENT_TOTAL_TOO_LARGE = 'ATTACHMENT_TOTAL_TOO_LARGE'
ATTACHMENT_COUNT_EXCEEDED = 'ATTACHMENT_COUNT_EXCEEDED'
ATTACHMENT_EMPTY = 'ATTACHMENT_EMPTY'
ATTACHMENT_NOT_FOUND = 'ATTACHMENT_NOT_FOUND'
ATTACHMENT_HASH_MISMATCH = 'ATTACHMENT_HASH_MISMATCH'
ATTACHMENT_STORAGE_FAILED = 'ATTACHMENT_STORAGE_FAILED'
ATTACHMENT_FILE_MISSING = 'ATTACHMENT_FILE_MISSING'
ATTACHMENT_PATH_OUTSIDE_ROOT = 'ATTACHMENT_PATH_OUTSIDE_ROOT'
FILE_CLIPBOARD_HELPER_SPAWN_FAILED = 'FILE_CLIPBOARD_HELPER_SPAWN_FAILED'
FILE_CLIPBOARD_HELPER_TIMEOUT = 'FILE_CLIPBOARD_HELPER_TIMEOUT'
FILE_CLIPBOARD_HELPER_FAILED = 'FILE_CLIPBOARD_HELPER_FAILED'
FILE_CLIPBOARD_OUTPUT_INVALID = 'FILE_CLIPBOARD_OUTPUT_INVALID'
FILE_CLIPBOARD_COUNT_MISMATCH = 'FILE_CLIPBOARD_COUNT_MISMATCH'
FILE_CLIPBOARD_PATH_MISMATCH = 'FILE_CLIPBOARD_PATH_MISMATCH'
TARGET_WINDOW_LOST_BEFORE_ATTACHMENT_PASTE = 'TARGET_WINDOW_LOST_BEFORE_ATTACHMENT_PASTE'
ATTACHMENT_PASTE_FAILED = 'ATTACHMENT_PASTE_FAILED'


class BroadcastError(Exception):
    def __init__(
        self,
        code: str,
        message: str | None = None,
        details: list[str] | None = None,
    ) -> None:
        super().__init__(code)
        self.code = code
        self.message = message or code
        self.details = details or []
