import type { BroadcastWorkspaceSnapshot } from './types';

export function createBroadcastWorkspaceSnapshot(): BroadcastWorkspaceSnapshot {
  return {
    scope: {
      botUuid: 'bot-1',
      connectorId: 'wxwork-local',
    },
    templates: [],
    variableProfile: {
      groupField: null,
      mappingRules: [],
    },
    variableMappings: [],
    groupRules: [],
    groupNames: [],
    importPreviewRows: [
      {
        id: 1,
        customerName: '华南物流',
        conversationName: '华南物流服务群',
        templateName: '到货提醒',
        variableSummary: '3 / 3 已就绪',
        status: 'completed',
        matchedRule: '完全一致',
      },
      {
        id: 2,
        customerName: '北辰零售',
        conversationName: '北辰零售服务群',
        templateName: '付款提醒',
        variableSummary: '2 / 3 已就绪',
        status: 'pending',
        matchedRule: '包含关键词',
      },
      {
        id: 3,
        customerName: '远海贸易',
        conversationName: '远海调度群',
        templateName: '客户跟进',
        variableSummary: '1 / 3 已就绪',
        status: 'failed',
        matchedRule: '规则已停用',
      },
    ],
    drafts: [
      {
        id: 101,
        botUuid: 'bot-1',
        connectorId: 'wxwork-local',
        customerName: '华南物流',
        conversationName: '华南物流服务群',
        templateName: '到货提醒',
        status: 'pending',
        draftText: [
          '您好，华南物流：',
          '货运单 SHP-2026-001 预计将在 2026-07-05 到达。',
          '请提前核对附件清单并安排收货。',
        ].join('\n'),
        progressLabel: '等待审核',
        updatedAt: '2026-07-02T08:40:00.000Z',
        operator: '林晓',
      },
      {
        id: 102,
        botUuid: 'bot-1',
        connectorId: 'wxwork-local',
        customerName: '北辰零售',
        conversationName: '北辰零售服务群',
        templateName: '付款提醒',
        status: 'failed',
        draftText: [
          '您好，北辰零售：',
          '发票 INV-20931 仍待确认。',
          '当前待处理金额：¥12,400。',
        ].join('\n'),
        progressLabel: '处理失败',
        updatedAt: '2026-07-02T08:05:00.000Z',
        operator: '周敏',
      },
      {
        id: 103,
        botUuid: 'bot-1',
        connectorId: 'wxwork-local',
        customerName: '远海贸易',
        conversationName: '远海调度群',
        templateName: '客户跟进',
        status: 'pasted',
        draftText: [
          '您好，远海贸易：',
          '王璐 已整理好后续跟进说明。',
          '备注：等待补充签收照片。',
        ].join('\n'),
        progressLabel: '已写入输入框',
        updatedAt: '2026-07-02T07:55:00.000Z',
        operator: '王璐',
      },
      {
        id: 104,
        botUuid: 'bot-1',
        connectorId: 'wxwork-local',
        customerName: '极地货运',
        conversationName: '极地货运交付群',
        templateName: '到货提醒',
        status: 'completed',
        draftText: [
          '您好，极地货运：',
          '货运单 SHP-2026-209 预计将在 2026-07-09 到达。',
          '请提前核对卸货安排。',
        ].join('\n'),
        progressLabel: '已完成',
        updatedAt: '2026-07-01T16:20:00.000Z',
        operator: '陈一',
      },
    ],
    executionLogs: [
      {
        id: 1,
        draftId: 101,
        customerName: '华南物流',
        conversationName: '华南物流服务群',
        status: 'pending',
        action: 'mock_prepare',
        message: '草稿已生成，等待人工审核。',
        timestamp: '2026-07-02T08:42:00.000Z',
      },
      {
        id: 2,
        draftId: 102,
        customerName: '北辰零售',
        conversationName: '北辰零售服务群',
        status: 'failed',
        action: 'mock_retry',
        message: '写入前校验失败，请检查变量内容。',
        timestamp: '2026-07-02T08:08:00.000Z',
      },
      {
        id: 3,
        draftId: 103,
        customerName: '远海贸易',
        conversationName: '远海调度群',
        status: 'pasted',
        action: 'mock_paste',
        message: '草稿内容已写入输入框。',
        timestamp: '2026-07-02T07:58:00.000Z',
      },
      {
        id: 4,
        draftId: 104,
        customerName: '极地货运',
        conversationName: '极地货运交付群',
        status: 'completed',
        action: 'mock_review',
        message: '审核完成，已归档本次记录。',
        timestamp: '2026-07-01T16:22:00.000Z',
      },
    ],
  };
}
